### ISSUE TITLE
add "Cool Reader" - my favorite FOSS ebook reader

### ISSUE THREAD

**Issue by DorianScholz** [repat/droid-break#17]
Thanks for your great listing of FOSS alternatives.
I can recommend "Cool Reader" as a great ebook reader with lots of features.
http://coolreader.org/e-index.htm
https://play.google.com/store/apps/details?id=org.coolreader
http://sourceforge.net/p/crengine/crengine/ci/master/tree/

**Comment by repat** [comment]
I will have a look at it, thanks:)

**Comment by repat** [comment]
added.
