### ISSUE TITLE
ttrss clients missing

### ISSUE THREAD

**Issue by lightonflux** [repat/droid-break#2]
in the news category there is already owncloud rss which depends on owncloud.

So i see no reason why the ttrss android apps should not be there. They depend on a ttrss installation somewhere but so does owncloud rss.

**Comment by repat** [comment]
Sure, just pick a good FOSS ttrss client and submit a pull request? :)

**Comment by repat** [comment]
Found any?

**Comment by ahstro** [comment]
I found <a href="https://f-droid.org/repository/browse/?fdfilter=ttrss&fdid=org.ttrssreader" traget="_blank">this</a>, but I've never used it, so I can't vouche for it. The score in the Play store is 4+, so I suppose it's good, but I'm not going to make a commit unless someone confirms that.

**Comment by lightonflux** [comment]
I used both for a longer period of time.

**TTRSS-Reader** is a fork of the official client

its Interface looks older and less polished, but has more configuration options (e.g. for broken SSL, not updating servers, DB actions etc). It worked much better offline than the official client and still does.

Looks like it has a Tablet UI. But i never used it on a Tablet.

https://play.google.com/store/apps/details?id=org.ttrssreader

**The official one** is [not available on F-Droid](https://f-droid.org/wiki/page/org.fox.ttrss) anymore – since a few days. Don't know why, it might change in the future.

It looks much more modern, and it's UI is more fancy and a easier to use. But it does not work well with bad internet connections (56kb/s | 7KB/s – but which devs nowadays care about that?). It has a Offline mode since a few month, which works, but it has to be enabled before using. It also has a Tablet UI, which i never used.

https://play.google.com/store/apps/details?id=org.fox.ttrss

Both apps work, sometimes even very well, if you have a good internet connection or resources. They both have minor issues that get fixed from time to time, until new appear. :)

**Comment by ahstro** [comment]
Just added a commit for TTRSS-Reader to my current pull request. I'll wait with making one for Tiny Tiny RSS since the F-Droid link you posted said this: "[...]Unable to reliably maintain - recommend using org.ttrssreader instead."

**Comment by repat** [comment]
added.
