### ISSUE TITLE
breack-droid "Failed to align recompiled APK"

### ISSUE THREAD

**Issue by Zain-0z** [repat/droid-break#20]
I was trying to embed a payload into an apk using breack-droid but every time it gives me this error

[ ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ ] 
[*] Generating apk payload
[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  ] 
[*] Removing 1.apk framework file...
[ ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ ] 
[*] Decompiling Original APK...
[ ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ ] 
[*] Decompiling Payload APK...
[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  ]rm: cannot remove 'Ball': No such file or directory
rm: cannot remove '4.apk': No such file or directory
 
[*] Adding permission and Hook Smali
[ ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++   ]rm: cannot remove '/root/break-droid/payload/smali/com/metasploit/stage/MainActivity.smali': No such file or directory
sed: can't read /root/break-droid/payload/smali/com/metasploit/stage/*.smali: No such file or directory
sed: can't read /root/break-droid/payload/smali/com/metasploit/stage/*.smali: No such file or directory

##################################################################
inject Smali: com/FDGEntertainment/redball4/gp/FixMultidexClass.smali
In line:13
##################################################################
[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  ] 
[*] Rebuilding Backdoored APK...
[ ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ ] 
[*] Checking for ~/.android/debug.keystore for signing...
[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++    ] 
[*] Attempting to sign the package with your android debug key
[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  ]
[*] Verifying signed artifacts...
[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  ]
[*] Aligning recompiled APK...
[ ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ ]Zip alignment utility
Copyright (C) 2009 The Android Open Source Project

Usage: zipalign [-f] [-p] [-v] [-z] <align> infile.zip outfile.zip
       zipalign -c [-p] [-v] <align> infile.zip

  <align>: alignment in bytes, e.g. '4' provides 32-bit alignment
  -c: check alignment only (does not modify file)
  -f: overwrite existing outfile.zip
  -p: memory page alignment for stored shared object files
  -v: verbose output
  -z: recompress using Zopfli

[✔] Done.
[ ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++   ] 
[!] Failed to align recompiled APK

**Comment by ahstro** [comment]
Hey @Mostafa733 😊 Looks like you're in the wrong place. This used to be the repo for [droid-break](https://droid-break.info), but it sounds like you might have confused it with [BreakDroid](https://forum.xda-developers.com/showthread.php?t=1527954). Better luck there!
