### ISSUE TITLE
Another source of apps

### ISSUE THREAD

**Issue by dalb8** [repat/droid-break#9]
Hi, I maintain my own f-droid repo, which is much smaller than the official f-droid repo but is well maintained (for now) and has plenty of stuff they don't have: https://gitorious.org/asdgasd/my-fdroiddata. I get most new apps from the Apps & Games forum of XDA or the F-droid forums.

**Comment by repat** [comment]
Don't really know how to include this. Other projects contacted me as well, maybe I can think of something...

**Comment by ahstro** [comment]
How would you vouch for the validity of the apps? F-Droid is pretty big and a lot of people use it so I'm prepared to trust them, but (and no offence) I feel a lot more uncomfortable downloading apps from some indie-repo. I don't believe that you would put malicious code in the apps, but what stops you from doing it? Do you have md5/sha hashes for every apk or something?

**Comment by dalb8** [comment]
There are no apks, only source code, so you can verify yourself. BTW most of the recipes on f-droid were added by myself, but I prefer to concentrate on my personal one now.

**Comment by dalb8** [comment]
I've just pushed 50 of the apps to f-droid, but there are still a few interesting items they won't have e.g. Network Location.

I prefer to cut out the middle-man , but if you want to trust their binaries you can still run $fdroid build -p com.example --verify which will try to build the exact apk; make sure you have a powerful machine though!

**Comment by repat** [comment]
I don't think there's any need for another repository. Google Play as the de facto standard for Android apps and F-Droid as the de facto FOSS standard repository are enough for the time being. A french guy suggested in the comments I could open my own F-Droid repository with just the apps _droid-break_ recommends, but that's quite a lot of work that doesn't bring any benefits. If you're really paranoid, just compile your own .apks. No need to trust Google, F-Droid or random people on the internetz, like you or me.

If something cool comes up, I'll reopen this issue.

**Comment by dalb8** [comment]
Google Play isn't a de facto on Android and a few people even take it off their phones. To get APKs they sometimes have to download via Google Play from evozi.com over http or via other app stores.  Somebody should set up a 'shadow' fdroid repo with APKs that are signed by the developer and delivered over https; it wouldn't be a huge amount of work if there was a little automation. 

I do actually compile 99% of my own apps as the OP says, though that doesn't solve all the security problems for sure. It's not so much paranoia and does actually solve the problems of availability of apps outside Google Play. For the other 1% I would use this shadow repo.
